export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const USER_MY_ORDERS_REQUEST = 'USER_MY_ORDERS_REQUEST'
export const USER_MY_ORDERS_SUCCESS = 'USER_MY_ORDERS_SUCCESS'
export const USER_MY_ORDERS_FAIL = 'USER_MY_ORDERS_FAIL'
export const USER_MY_ORDERS_RESET = 'USER_MY_ORDERS_RESET'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'

export const USER_DETAILS_ADMIN_REQUEST = 'USER_DETAILS_ADMIN_REQUEST'
export const USER_DETAILS_ADMIN_SUCCESS = 'USER_DETAILS_ADMIN_SUCCESS'
export const USER_DETAILS_ADMIN_FAIL = 'USER_DETAILS_ADMIN_FAIL'

export const PRODUCT_LIST_ADMIN_REQUEST = 'PRODUCT_LIST_ADMIN_REQUEST'
export const PRODUCT_LIST_ADMIN_SUCCESS = 'PRODUCT_LIST_ADMIN_SUCCESS'
export const PRODUCT_LIST_ADMIN_FAIL = 'PRODUCT_LIST_ADMIN_FAIL'

export const PRODUCT_DETAILS_ADMIN_REQUEST = 'PRODUCT_DETAILS_ADMIN_REQUEST'
export const PRODUCT_DETAILS_ADMIN_SUCCESS = 'PRODUCT_DETAILS_ADMIN_SUCCESS'
export const PRODUCT_DETAILS_ADMIN_FAIL = 'PRODUCT_DETAILS_ADMIN_FAIL'

export const ADMIN_PRODUCT_UPDATE_REQUEST = 'ADMIN_PRODUCT_UPDATE_REQUEST'
export const ADMIN_PRODUCT_UPDATE_SUCCESS = 'ADMIN_PRODUCT_UPDATE_SUCCESS'
export const ADMIN_PRODUCT_UPDATE_FAIL = 'ADMIN_PRODUCT_UPDATE_FAIL'
export const ADMIN_PRODUCT_UPDATE_RESET = 'ADMIN_PRODUCT_UPDATE_RESET'

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

export const PRODUCT_ADD_REQUEST = 'PRODUCT_ADD_REQUEST'
export const PRODUCT_ADD_SUCCESS = 'PRODUCT_ADD_SUCCESS'
export const PRODUCT_ADD_FAIL = 'PRODUCT_ADD_FAIL'
export const PRODUCT_ADD_RESET = 'PRODUCT_ADD_RESET'

export const ORDER_LIST_ADMIN_REQUEST = 'ORDER_LIST_ADMIN_REQUEST'
export const ORDER_LIST_ADMIN_SUCCESS = 'ORDER_LIST_ADMIN_SUCCESS'
export const ORDER_LIST_ADMIN_FAIL = 'ORDER_LIST_ADMIN_FAIL'

export const ORDER_DETAILS_ADMIN_REQUEST = 'ORDER_DETAILS_ADMIN_REQUEST'
export const ORDER_DETAILS_ADMIN_SUCCESS = 'ORDER_DETAILS_ADMIN_SUCCESS'
export const ORDER_DETAILS_ADMIN_FAIL = 'ORDER_DETAILS_ADMIN_FAIL'